### PR TITLE
Add "Disabling Google Sync" section

### PR DESCRIPTION
**Pull request by Hammerill**
As descripted in here: https://github.com/salesagility/SuiteDocs/issues/639

### CODE REVIEW

**Comment by pgorod** [comment]
Thank you for this :+1:

**Comment by serhiisamko091184** [comment]
Hey @Hammerill, 

thanks for contributing to SuiteCRM project,

I'd like to check if there's a particular reason to 'delete the task'.   

image

Is that possible to achieve the same result with just the deactivation of the task?
image

image

Thanks in advance. 

Regards,
Serhii

**Comment by Hammerill** [comment]
Hello @serhiisamko091184,
And indeed, there was no particular reason to delete the task, that was my error. It should be `Disable (or delete)` as at the end.

**Comment by serhiisamko091184** [comment]
Thanks for your quick response and update @Hammerill!

If there's no need to delete it, maybe it is better to focus on Disabling / Enabling (or Activating / Deactivating)?   

It's more convenient to have the task handy if you want to use it again, rather you need to create the same one later on. 

What are your thoughts? 

Thanks! 

Regards,
Serhii

**Comment by Hammerill** [comment]
That's right @serhiisamko091184, there's no need in deleting these tasks, thank you. I will remove any trace of that.

**Comment by serhiisamko091184** [comment]
Thank you @Hammerill!

**Comment by Hammerill** [comment]
Hello @serhiisamko091184 , thank you for these suggestions, I've made the section more consistent.

**Review by serhiisamko091184 — APPROVED** [review]

**Comment by serhiisamko091184** [comment]
Hey @Hammerill, 

thanks for your cooperation and quick changes!

Regards,
Serhii

**Pull request merged**
