### PR TITLE
Add Google Sync and Elasticsearch translation 

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @likhobory!

Are you coming to the PR Party today? If so, please register here: 
https://gitter.im/suitecrm/Lobby

**Comment by likhobory** [comment]
Hi Pedro!

I'll be online today not so long, but I'll try to register.

**Comment by pgorod** [comment]
I am thinking - the `russian` branch has the work you did to split the User guide into more pages, which is waiting for me to replicate on the English site before it can be merged.

If this PR was on a separate branch, I could merge it without having to wait for that.

**Comment by likhobory** [comment]
No, this PR does not contain splitted User guide, 

see bdown-UI branch for splitted pages: https://github.com/likhobory/SuiteDocs/commits/bdown-UI and I plan to update them in a few days.

**Comment by pgorod** [comment]
@likhobory there seems to be something wrong with this branch, because I am seeing too much extra stuff in this PR: 72 commits, 115 changed files...

Maybe you need to bring the branch in your repo up-to-date with our repo, so that only the correct commits appear in this PR.

**Comment by likhobory** [comment]
I updated my repo before..
Maybe this this is because the Russian branch on your repo has not been updated for a long time, I'm right?

**Comment by pgorod** [comment]
I had updated it just before writing my message. But now I realize I did it wrong, in reality I was updating my `pgorod\SuiteDocs` repo, instead of `salesagility\SuiteDocs`.

I will have to get this straightened out tomorrow, sorry, my bad.

**Comment by pgorod** [comment]
`git` is really freaking me out on this one. I have brought the branch up to date, but it still shows 73 commits, 115 files changed.

But if I do the compare starting from your repo, it says this instead:

https://github.com/salesagility/SuiteDocs/compare/russian...likhobory:master

This looks right on your repo, but not in the PR here? I can't figure out why.

**Comment by pgorod** [comment]
Seen from there, yes.

But at the top of this PR, it says:
image

While if I start [the same comparison from your repo](https://github.com/salesagility/SuiteDocs/compare/russian...likhobory:master), it says:

image

So it even recognizes (see my blue line) it that a PR already exists for that comparison, but gives a different commit and file count? 

I think this is some bug. Maybe I will close this PR and start a new one from your same branch.

**Comment by likhobory** [comment]
Hmm, Curiouser and curiouser!

**Pull request closed without merging**
