### PR TITLE
Update Release Notes with New Version 7.10.21 & 7.11.9

### PR DESCRIPTION
**Pull request by Mac-Rae**

### CODE REVIEW

**Comment by connorshea** [comment]
Can we mention the upcoming PHP 5.5 removal in these release notes? @samus-aran @Mac-Rae @pgorod @Dillon-Brown

**Comment by pgorod** [comment]
Sounds like a good idea to me, it would give people more time to prepare.

How would yo phrase that? And do we include some link to the discussion?

**Comment by connorshea** [comment]
Something like this?

```
BREAKING CHANGE NOTICE:

We intend to drop support for PHP 5.5 in the next release of SuiteCRM 7.10.x. We'll continue to support PHP 5.6 and greater.

We're making this change because many of our dependencies have dropped support for 5.5, and we're unable to update them until we also drop it. Continuing to support 5.5 causes a significant maintenance burden for our team and community, and prevents us from moving forward with many improvements to the CRM.

If you have any comments or concerns about this change, please comment at https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27442-dropping-support-for-php-5-5-in-the-next-7-10-x-release or https://github.com/salesagility/SuiteCRM/issues/7463.
```

**Comment by pgorod** [comment]
I like it. I suggest just a few minor changes
```
BREAKING CHANGE NOTICE:

We intend to drop support for PHP 5.5.9 in the next release of SuiteCRM 7.10.x. We'll continue to support PHP 5.6 and greater.

We're making this change because many of our dependencies have dropped support for 5.5.9, and we're unable to update them until we also drop it. Continuing to support 5.5.9 causes a significant maintenance burden for our team and community, and prevents us from moving forward with many improvements to the CRM.

If you have any comments or concerns about this change, please comment [in this Forum thread](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27442-dropping-support-for-php-5-5-in-the-next-7-10-x-release) or [in this Github Issue](https://github.com/salesagility/SuiteCRM/issues/7463).
```

Just changed 5.5 to 5.5.9 and _textified_ the links.

Note that I didn't fully follow the PHP 5.5 deprecation discussion, are we decided on this?

**Comment by connorshea** [comment]
I don't know if we've come to a complete conclusion here, I've not gotten a totally solid answer yet.

**Comment by Dillon-Brown** [comment]
Might be worth putting in the migration [guide](https://www.php.net/manual/en/migration56.php)? the backwards-incompatible changes are actually really small going from 5.5.9 to 5.6 imo.

For the actual decision of deprecating 5.5 in a particular release, afaik it hasn't actually been made yet but I'll re-raise it on Monday and see where we got with it from our previous discussions. Thanks for all the work you've done on this and everything else @connorshea :).

**Pull request closed without merging**
