### PR TITLE
WIP Adding SuiteCRM Analytics Documentation

### PR DESCRIPTION
**Pull request by samus-aran**

### CODE REVIEW

**Comment by pgorod** [comment]
@samus-aran I suggest creating a new branch here on `salesagility/SuiteDocs` repo to work on this. This makes it much easier for more than one person to collaborate on the work, which might be the case here? Not sure. 

Remember you can also mark your PR as `Draft` so that Github knows (and shows) it's a WIP.

**Comment by samus-aran** [comment]
Thanks Pedro, I missed the mark to make it into a draft PR.  I don't need to make this into a branch just yet. This is only the initial phase for the Analytics documentation. There will be more once this is merged into master

**Comment by samus-aran** [comment]
Sourceforge is currently down, but surely that wouldn't have an affect on the build :(

**Comment by samus-aran** [comment]
Tried something and failed :( sorry for all the alerts :stuck_out_tongue_closed_eyes:

**Comment by pgorod** [comment]
No problem. 

**Tip**: imagesdir is better as an absolute path:

`:imagesdir: /images/en/user`

Only links to pages should be relative (this is because of the way different languages are handled).

**Pull request merged**
