### PR TITLE
Update Russian Docs for SuiteCRM 8.x / 7.13+

### PR DESCRIPTION
**Pull request by likhobory**
----------------
Main changes (8.5):
- [Update Compatibility Matrix.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/2d97bef7c4768847ebe76eaacdb6a12031c82c90)
- [Add quick-filters.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/dc3de04b2a456b9151b396bdce090f441635e702)

----------------
Main changes (8.4):
- [Update Compatibility Matrix.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/13c49fd825313d596fae5c63240b8e65f64ec250)
- [Add Trusted-Hosts-Configuration.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/840987c9bd8eef637ba151efe99aaa9472463570)
----------------
Main changes (8.3):
- [Update Compatibility Matrix.ru.adoc](https://github.com/salesagility/SuiteDocs/pull/582/commits/cc5ae50f9b1217cbefee8b8422daef1c26e23582)
- [Add Admin Page Documentation (Russian)](https://github.com/salesagility/SuiteDocs/pull/582/commits/9e92d14bfd68b32b680faec6616a24427c3b1451)
- [Add load-more.ru.adoc, notifications.ru.adoc and subpanel-filtering.ru.adoc](https://github.com/salesagility/SuiteDocs/pull/582/commits/e060744af654d87c5e74bbcb7de6eb839f5aec1e)
- [Split Downloading & Installing.ru.adoc into webserver-setup-guide.ru.adoc, running-the-cli-installer.ru.adoc & running-the-ui-installer.ru.adoc](https://github.com/salesagility/SuiteDocs/pull/582/commits/49c1998f7a49ca069badc21b173358822fd7c2f7) 
----------------
Main changes (8.2):
- [Update Compatibility Matrix.ru.adoc](https://github.com/salesagility/SuiteDocs/pull/582/commits/6e8fd87b67d042a6008dc15c6f7b15c71fb32da2)
- [Update Upgrading.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/60238315050bd7370d3f1cc48edacaacbc0f8166)
- [Update Legacy-Migration.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/d486fcf2a9762dcceac65d92b9aeca3a1144960a)
-  [Add Performance.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/bf1dbdec6adefea5c6d7a2ec65a47d689707306e)
- [Add Sessions-Configuration.ru.adoc](https://github.com/salesagility/SuiteDocs/pull/582/commits/f2855d683b36cdd96e8043ea629dd356e5380c47)
- [Add Login-Throttling-Configuration.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/add31adcf4b5ff9aa7f9999ae5696c80bb4deffd)
- [Add LDAP-Configuration.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/40a5e1411244f616cfae8c766c19c1d79767a4b1)
- [Add SAML-Configuration.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/6ce84807376a411aa51cb314cdba16682e5861fc)
----------------
Main changes (7.14):
- [Update Compatibility Matrix.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/13c49fd825313d596fae5c63240b8e65f64ec250)
- [Add Azure SAML Single Sign On Documentation (Russian)](https://github.com/likhobory/SuiteDocs/commit/22c72c57203a8a28392494a815b62b504ac94aa0)
----------------
Main changes (7.13):
- [Update Compatibility Matrix.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/d3ce57cc17f95e7643136d17cacb6dded6e15396)
- [Add Microsoft-OAuth-Provider-HowTo.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/33e406d5104d7b067668f34272290b8c1fbdd1cf)
- [Add InboundEmail-OAuth-HowTo.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/4fac711af1b9e849a645f009fe831d6cb43ffe90)
- [Add OAuth-Provider-Overview.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/09cfed628d3fdb762868ec283b562d1bd35b89d2)
- [Add InboundEmail-SecurityGroups.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/bbd7bfd7b265eda2357e8020d4c685e359e3cc08)
- [Update content/admin/administration-panel/Emails/Email.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/ffce1775cdbc7f447ef2f37041d4726fa6da8160)
- [Update content/user/core-modules/Emails.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/01edd62400712166560d081d3511e5d0fafb8306)
- [Add Email-Compose-From-List.ru.adoc](https://github.com/likhobory/SuiteDocs/commit/bc2a09d18254bb5bbc790dc32cbee24150e26297)

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @likhobory , happy new year 🎉 

Unrelated to this PR, I just dropped by to let you know about this, I am sure you'll find it interesting:

https://discourse.gohugo.io/t/asciidoctor-server/47475

That developer benchmarked the Hugo build of SuiteDocs and

> Normally, it took 60-65 seconds to build. With asciidoctor-server it took 10-12 seconds.

Another interesting one (that I haven't tried yet):

https://discourse.gohugo.io/t/hugo-preview-panel-for-vscode-inspired-by-the-convenience-of-built-in-markdown-preview/47569

**Comment by likhobory** [comment]
Hi @pgorod.
Thanks for the links and (better late than never) my congratulations on Christmas and Happy New Year!

**Comment by serhiisamko091184** [comment]
Hello @likhobory 

Thanks for this amazing contribution and all the changes you've been doing so far, 

After checking the files and the UI I'm almost ready to bring this commit up to the code base. 

I'd like you to have a look at some possible slight and minor corrections/suggestions (attached). 
[ru_docs.odt](https://github.com/salesagility/SuiteDocs/files/14524273/ru_docs.odt)

When you update this PR, I'll be ready to check everything one more time and proceed with merging. 

Thanks in advance! 

Regards,
Serhii

**Comment by likhobory** [comment]
Hi @serhiisamko091184 
Thank you for your valuable comments, I hope everything you mentioned has been fixed except points 5-8. I can't find the specified commits, could you please write filenames that require fixes instead of hashes?

**Comment by serhiisamko091184** [comment]
Hey @likhobory,

thanks for your quick reply and cooperation,  

yes, sure: 

5) Commit 190798c7 – same as item 4 L48.

It’s optional as well. 

File; content/user/advanced-modules/Sales.ru.adoc
There are a lot of links to the dev or admin section present. That is clear that the admin is also a user, a privileged one, though EN documentation is more focused on regular user interaction with the UI.     

6) Commit e48fee34 – could you please clarify what is the purpose for commenting out the section on configuring table height?

File: content/8.x/features/load-more.ru.adoc

image

7) Commit bab16263 – as we are up to update documentation there’s no need to bring this commit into the code base.

File: README.ru.adoc
image

8) Commit 3f9a6b85:
	content/8.x/features/load-more.ru.adoc: same as  e48fee34.

File: content/8.x/features/load-more.ru.adoc
image

The section on configuring table height is commented out. Is it going to be translated and added? 

        content/8.x/features/notifications.ru.adoc (optional): there are several sections absent (snoozing, dismissing, etc.) 

File: content/8.x/features/notifications.ru.adoc
image

There are more chapters on this page in EN version of documentation - Snoozing, Dismissing and Load more.

Thanks a lot! 

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
@likhobory, would you be so kind to have a look at Netlify deploy log - particularly related to RU documentation: 

image
  
7:04:49 PM: hash does not exist --- ru/8.x/admin/administration-panel/administration-panel/index.html --> ../../../../admin/administration-panel/emails/email/#_настройка_e_mail
7:04:49 PM: target does not exist --- ru/admin/administration-panel/users/index.html --> ../email/#_входящие_e_mail
7:04:49 PM: target does not exist --- ru/admin/administration-panel/users/index.html --> ../email/#_настройка_e_mail
7:04:49 PM: target does not exist --- ru/admin/administration-panel/system/index.html --> ../email/#_входящие_e_mail
7:04:49 PM: target does not exist --- ru/admin/installation-guide/downloading-installing/index.html --> ../../administration-panel/email/#_настройка_e_mail
7:04:49 PM: target does not exist --- ru/user/modules/confirmed-opt-in-settings/index.html --> ../../../admin/administration-panel/email/#_настройка_e_mail
7:04:49 PM: target does not exist --- ru/user/core-modules/cases/index.html --> ../../../admin/administration-panel/email/#_настройки_групповой_учётной_записи
7:04:49 PM: target does not exist --- ru/user/core-modules/campaigns/index.html --> ../../../admin/administration-panel/email/#_исходящие_e_mail
7:04:49 PM: target does not exist --- ru/user/core-modules/campaigns/index.html --> ../../../admin/administration-panel/email/#_параметры_рассылки_e_mail
7:04:49 PM: target does not exist --- ru/user/core-modules/campaigns/index.html --> ../../../admin/administration-panel/email/#_настройки_учётной_записи_для_обработки_возвращаемой_почты
7:04:49 PM: target does not exist --- ru/user/core-modules/emails/index.html --> ../../../admin/administration-panel/email/#_настройки_групповой_учётной_записи

For instance:
7:04:49 PM: target does not exist --- ru/user/core-modules/emails/index.html --> ../../../admin/administration-panel/email/#_настройки_групповой_учётной_записи

image

image

Many thanks in advance! 

Regards,
Serhii

**Comment by likhobory** [comment]
@serhiisamko091184 
>Commit bab16263 – as we are up to update documentation there’s no need to bring this commit into the code base.
File: README.ru.adoc

The question is how quickly and regularly such updates will be performed.
@pgorod updated the documentation quite quickly :+1: and I hope you'll follow his lead.
Вut if the next update is in another 2 years, then the proposed formulation is very relevant.

**Comment by serhiisamko091184** [comment]
Hello @likhobory,

thank you for the changes and feedback,

need time to check it once more.

Thanks a lot! 

Regards,
Serhii

**Review by serhiisamko091184 — APPROVED** [review]

**Comment by serhiisamko091184** [comment]
Thanks a lot for your cooperation one more time, @likhobory!

Regards,
Serhii

**Comment by likhobory** [comment]
@serhiisamko091184 
Thanks, could you tell me please when the russian branch will be merged with the master branch?

**Comment by serhiisamko091184** [comment]
Hello @likhobory, 

Apologies for the delayed response, 

I'll try to get it merged during the current week, I'll update you when it's ready. 

Thanks a lot! 

Regards,
Serhii

**Pull request merged**
