### PR TITLE
Minor editorial changes to improve readability.

### PR DESCRIPTION
**Pull request by genezak**

### CODE REVIEW

**Comment by pgorod** [comment]
@genezak first let me start by thanking you for taking an interest in helping out, and starting this edit.

But I have my doubts on this one... you see, SecuritySuite is the name of an add-on, which existed before SuiteCRM (in the SugarCRM days) and still exists today, you can buy a professional version to get extra features:

https://store.suitecrm.com/support/securitysuite/

Also, if we were really to change this, we would need to do it consistently across all instances where it appears:

https://github.com/salesagility/SuiteDocs/search?q=SecuritySuite&unscoped_q=SecuritySuite

But I really think we need to leave the name as it  is, we owe it to the makers of that add-on who were very generous to let us have it in the first place.

**Comment by samus-aran** [comment]
Agreed @pgorod 
Thanks for your suggestions but as SecuritySuite is similar to branding (like SuiteCRM) that we will maintain it's name as is.

**Comment by genezak** [comment]
Hello! Thanks for your follow up and clarifications! Totally understand regarding branding and credits. Let me just provide with more specifics and advocate suggested updates bit more.

Here is what are the suggested changes in short:
(a) "SecuritySuite is very configurable" --> "Security Suite is very configurable"
(b) "on your SecuritySuite Settings" --> "on your Security Suite Settings"
(c) "...the group, but who should see be able to see..." --> "...the group and who should also be able to see..."
(d) "...a role directly assigned to you..." --> " a role assigned directly to the manager's
record..."
(e) "SecuritySuite" --> "Security Suite"
(f)  "...common scenario it is used for is one where.." --> "...common scenario is one where..."
(g) "...can see both their own records and those of their..." --> "...can see both their own records as well as those of their..."

(a) refers to add-on, agreed with your justification to skip
(b) my understanding - this refers to Admin/Security Suite Setting panel navigational endpoint, thus a similar spelling, pls correct if I am mistaken.
(c) "see be able to see" - erroneous wording
(d) improved wording to help the message be more clear
(e) refers to add-on, agreed with your justification to skip
(f) and (g)  improved wording to help the message be more clear

Hope this clarifies, thanks for looking into this!
Cheers.

**Comment by pgorod** [comment]
Thanks, I've changed the things you mention

https://github.com/salesagility/SuiteDocs/commit/2f07771e35695fb73cd59ed4c5451ee6df0fc2bb

Admittedly, there are still inconsistencies, the app itself has some labels with the space between the words: `Security Suite`, and this is reflected in some expressions here in the Docs. We'll have to improve on all this one day.

**Pull request closed without merging**
