### PR TITLE
Add Russian translation for "Preparing for a Larger Upgrade" post

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
It is not necessary, but if you want to translate the graph, here is the file I created:

[Migrate.zip](https://github.com/salesagility/SuiteDocs/files/3694908/Migrate.zip)

Unzip it and you can open it (and edit it) here: https://www.draw.io/

**Comment by likhobory** [comment]
Thanks Pedro :+1:

**Comment by pgorod** [comment]
I am a bit confused now, what is in this PR?

- the new blog page, in Russian

- the latest PR's from other people that were merged into master

- all the `imagesdir` fixes

Is this correct?

**Comment by likhobory** [comment]
Yes, yes and yes :)

**Comment by samus-aran** [comment]
Hey @likhobory  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by likhobory** [comment]
> your shipping details

It's all right, thanks 👍

**Pull request merged**
