### PR TITLE
Add some translation to community section

### PR DESCRIPTION
**Pull request by likhobory**
To avoid 404 error when clicking some links from Russian home page.
All files with untranslated content are marked as 'англ.' (en)

### CODE REVIEW

**Comment by likhobory** [comment]
To avoid 404 error when clicking some links from Russian home page. 
All files with untranslated content are marked as 'англ.' (en)

**Comment by pgorod** [comment]
Hi @likhobory. Sorry for not looking at this earlier, I've been too busy...

From what I understand. you're adding a lot of Russian files (`.ru.adoc`) with English content, as placeholders to avoid broken links? And then your plan is to translate them later?

What about the Spanish files, why are you including them? Maybe the PR needs a little clean up?

Thanks!

**Comment by likhobory** [comment]
Hi Pedro,

>you're adding a lot of Russian files (.ru.adoc) with English content, as placeholders to avoid broken links?

Yes,  but some files have been translated (all files in the 'Contributing to the Documentation' section). I do not plan to translate English content in the developer section (at least in the near future), but I think it's better to publish it now for Russian users 'AS IS': it will be better for web search engines and for advanced users/developers (a large number of the developers prefer native English documentation).

>What about the Spanish files, why are you including them?

I did not add them specially, I just updated my forked branch from the salesagility/SuiteDocs master branch and added my translation into it. Where is the mistake?

**Comment by pgorod** [comment]
About the Spanish files: you need to bring your master branch up-to-date with ours every time, just before you start a pull request. 

Anyway,  I will cherry-pick the correct commits from your branch, don't worry.

I am hesitant to put untranslated content into files with `.ru` extension. This adds significantly to our build times, which are already becoming a nuisance. And it's confusing for users. I think people should just browse the English site if they're looking for English content, or if that is the only content there is for that section.

**Comment by likhobory** [comment]
>This adds significantly to our build times, which are already becoming a nuisance.

ok, I'll close this PR and open new one with translated files for the 'Contributing to the Documentation' section.

**Pull request closed without merging**
