### PR TITLE
Break down Releases

### PR DESCRIPTION
**Pull request by likhobory**
I also  propose  to use children shortcode `{{% children %}}` in the English version of the file content/admin/releasepages/_index.ru.adoc. This will simplify updating the TOC.

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory there's a nice new Github features called "Draft PR's". You can use it instead of the prefix "WIP", just select a Draft when opening the PR, and then when it's ready change it to a normal PR.

**Comment by likhobory** [comment]
There are several disadvantages when users navigating through a new tree of releases :
 - When user updating any manual page, the upper part of the TOC is displayed all the time, in this case the upper part of the "Administrator Guide" section. To view another release you have to scroll down the TOC all the time.
  - Two new SuiteCRM branches are released per year, so the existing list of releases will be constantly updated and will become longer and longer. This makes access to the below help sections less convenient.
  
  I propose to move the release section to a separate top-level section, so the 'Releases' section will not impede access to other sections:
  1 User Guide
  2 Developer Guide
    ............
 5 Releases

@pgorod @cameronblaikie  What do you think about this??

**Comment by pgorod** [comment]
I don't think we need to move it someplace else, but you are right that we need to do something about the sidebar menu.

We can control which entries appear there by preceding the title with a `discrete` attribute, like this:

```
[discrete]
== 7.4.3
```

I think `discrete` should only be used rarely, there was a time when these were all over the place and I removed quite a few. Normally the menu works well by automatically expanding and collapsing, according to where you are. 

But in some cases (like these sub-releases) I guess it's better to hide the excessive entries...

**Comment by likhobory** [comment]
Agree, in this case I propose to remove unnecessary [discrete] attributes from releases description. But I also propose to add for the English version the TOC (:toclevels: 1) at the beginning of each file, so that users can quickly move inside the file to view the desired subrelease, which is especially important for viewing TLS releases, see Russian example: https://deploy-preview-231--suitedocs.netlify.com/ru/admin/releasepages/7.8.x/

**Comment by pgorod** [comment]
Yes I want to add the toc entries at the beginning, they are quite useful. 

The old `releases.adoc` file had a manual toc because it was huge and it was easier to make it shorter (a comma-separated list) by doing it manually. But now we can just do things the standard way, and use automatic tables of contents.

I won't have time to work on this soon (off for vacations at the end of the week) but maybe @cameronblaikie will have a chance?

**Comment by likhobory** [comment]
It is not difficult for me to add TOC to the English version, I'll add it by analogy with the Russian files and remove unused [discrete] attributes..

**Comment by pgorod** [comment]
Thanks!

That exposed a few bugs in the English titles: some "Assets" that have the wrong heading level, and the label LTS that needs to be made more consistant.

But other than that, it's looking good.

**Comment by likhobory** [comment]
>wrong heading level

I'll fix it in the next commit for both languages.

**Comment by likhobory** [comment]
Done.

**Comment by pgorod** [comment]
@likhobory thanks a lot for all that work.

I am a bit hesitant about adding those bolds in Headings like `=== *Title*`, because they break the rule of trying to separate content from formatting as much as possible, and they reduce the consistency of the design across pages.

If we need to differentiate more the aspect of Level 2 and Level 3 headings, we should be doing it in the stylesheet, not in individual headings.

But I don't mind merging this as it is and fixing it later when we have the time. I'm off for vacations and will be away until the middle of next week.

**Comment by likhobory** [comment]
I was guided by the fact that in the description of release 7.11 there are headings like `=== * Title *` and I just saved the already existing design. But I agree with you, we should be doing it in the stylesheet.
So, I'll clean up the headings in the next commit.

Have a nice rest ))

**Pull request merged**
