### PR TITLE
Move Translation / Language packs site into Docs site #207

### PR DESCRIPTION
**Pull request by cameronblaikie**
Move Translation and Language packs site into Docs site 

issue ref - #207

### CODE REVIEW

**Comment by pgorod** [comment]
@horus68 I was trying to ask for your review on this, but I don't get the option to add your name when I press "Reviewers" (top right of this screen).

So I thought I could try adding you as a "Collaborator" of this repo, which I did the day before yesterday. But you need to accept that, did you get an email with the invitation? If not, please go to this link

https://github.com/salesagility/SuiteDocs/invitations

Thanks

**Comment by pgorod** [comment]
@horus68 any news on this?

**Comment by horus68** [comment]
no time yet :( 
Hope next week will be different!

**Comment by pgorod** [comment]
@cameronblaikie this PR got messed up because it was done prior to that big change I made rewriting Git history in this Repo. 

Do you think you can redo the PR (start a new one) with just your two commits? I think you would need to cherry-pick your commits into a new branch, I don't know exactly how to do it but I am sure @Dillon-Brown can do it with his eyes closed, so he should be able to help you out...

**Comment by pgorod** [comment]
@cameronblaikie can we advance this one? Tell me if you need help with git.

@horus68 we need your validation on this one, and we need to sync with you so you can pick a good time to remove your other site. Is now a good time (with school vacations and all)?

**Comment by horus68** [comment]
No problem on y side. You an move on with this. It will easy to create a redirect to the new site.

**Comment by pgorod** [comment]
Ok @horus68 this is merged, should be up in a couple of minutes, if you can please do the redirect I would appreciate it. Thanks.

**Comment by pgorod** [comment]
I made a bunch of fixes to the Asciidoc source and pushed again.

The correct entry link is 
http://docs.suitecrm.com/admin/installation-guide/languages/install-a-new-language/

**Comment by horus68** [comment]
@pedro-gr you used the old files (text and images): it was done with old suitCRM screens
Can you please update the site:
Sources:
Install: https://sites.google.com/site/translatingsuitecrm/faq/install-new-languages
Updating https://sites.google.com/site/translatingsuitecrm/faq/updating-languages

and maybe a page for the Crowdin FAQ screens:
https://sites.google.com/site/translatingsuitecrm/translate
https://sites.google.com/site/translatingsuitecrm/faq/crowdin-filters

**Pull request merged**
