### PR TITLE
Feb20releasenotes

### PR DESCRIPTION
**Pull request by Mac-Rae**
Should:

- Add release notes for both 7.11 and 7.10 releases
- Fix site CSS issue where the navbar is larger than search
- Fix site CSS issue where guide header is out of line

Please let me know if you encounter any issues

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Working on fixing issue :+1:

**Comment by Mac-Rae** [comment]
@pgorod that should be it!

**Comment by pgorod** [comment]
@Mac-Rae if you pull the commit I made just now, you can use the new shortcode for the contributors list:

`{{% ghcontributors connorshea 604media Abuelodelanada lazka re8260 ApatheticCosmos pgorod QuickCRM %}}`

**Comment by samus-aran** [comment]
Identify we'll do the comment in a later PR. Thanks Pedro :+1:

**Pull request merged**
