### PR TITLE
Htmltest

### PR DESCRIPTION
**Pull request by pgorod**

### CODE REVIEW

**Comment by likhobory** [comment]
Hi Pedro, 
Pay attention to the wrong link in the current update in System.ru.adoc file, it should be left unchanged:
`link:../../installation-guide/upgrading[Обновление системы].`

**Comment by likhobory** [comment]
> I will ask for your help to break down your largest file 
Of course I'll help, but the largest file is Releases.adoc  and  I guess it will be  increase..
maybe it is worth replacing the contents of the Releases.ru.adoc file with a link to English version?

**Comment by pgorod** [comment]
Yes, I'm also thinking of breaking down Releases.adoc (one for 7.7., one for 7.8, etc), but for some reason this huge file is not giving me the timeout problems. It might be because it doesn't have images and other complex formatting.

**Comment by likhobory** [comment]
>break down ... "user interface" in 3 smaller files

I suggest to put all "user interface" sections into 8 separate files and put all of them into "user interface" folder:
/user interface
Navigation Elements.adoc
Home Page.adoc
Search.adoc
.....

**Comment by pgorod** [comment]
Are you talking about the English version or the Russian, or both? :)

I am not sure they have the same structure now, do they?

**Comment by pgorod** [comment]
Ok, go ahead, I will do the English version (I really hope I can find the time - it won't be easy)

**Comment by likhobory** [comment]
Done for the Russian version.
Can I make PR into Russian branch or maybe in a new one?

**Pull request merged**
