### PR TITLE
Add Russian RAPIRA application guide.

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory thank you so much for this, this is amazing work you've done here.

I've been having a look at it in my local install, I need to add a few things to `config.toml` so that the site recognizes the Russian language in the language menu.

I also tried it in smaller resolutions and there is a problem (maybe unavoidable) because the words are quite long:

image

Do you think any of the words in the top menu could be shortened, or replaced by shorter words? especially the ones for `Edit this Page` and `Issue`? Thanks!

**Comment by likhobory** [comment]
I agree that Russian words are not the most compact. 
Try to replace 'Ошибка на странице' with 'Ошибка',     
perhaps this will be enough to solve this issue.

**Comment by pgorod** [comment]
@likhobory we were looking at your PR today. We pulled your changes into a branch so we could edit some things:

 https://github.com/salesagility/SuiteDocs/tree/russian

1So we want to do any changes there (we won't be merging this PR here, we'll just merge from that branch when it's ready). If you do any more changes, please pull from that branch first, and then direct a new PR to that branch.

Now, for the specific issues we found:

1. there are many links using a special `ifdef` construct:

```
ifndef::env-github[link:/user/introduction/user-interface.ru/#_Импорт_данных[импортировать]]
ifdef::env-github[link:/content/user/Introduction/User%20Interface.ru.adoc/#Импорт-данных[импортировать]]
```

We don't deploy on Github, these links should be simplified to just a basic link, preferably a relative one. 

2. Many internal links were broken, they need to be checked... (we plan to have automated link checking soon, but it's not in yet).

3. The same goes for images. Claire (@CBeechey) has fixed a few, I'm not sure if all of these broken images.

Tell me if you're using a different local environment than the one suggested [here](https://docs.suitecrm.com/community/contributing-to-docs/local-setup/). I ask because of your `ifdef::env-github` codes...

Thanks once again.

**Comment by likhobory** [comment]
>If you do any more changes, 

No, the content is not changed.

>Tell me if you're using a different local environment than the one suggested here. I ask because of your ifdef::env-github codes...

I used the suggested environment , but I  specifically added ifdef::env-github construct. I also use this content at [this](https://github.com/likhobory/SuiteAsciiDocRU) github rep. in order to be able to refer to different versions of this Russian manual if it will be necessary in the future. And I really  would like not to change these constructs if possible.

**Comment by likhobory** [comment]
>Many internal links were broken... 

About https://github.com/salesagility/SuiteDocs/commit/0f92574ece7078961ff97813ed0bdeacfc8727ed commit:

`ifndef::env-github[link:/user/introduction/user-interface.ru/#_Импорт_данных[импортировать]]`

This link is not working without '.ru' extension, tested with hugo 0.37 with recommended parameters. What hugo version you are using?

**Comment by pgorod** [comment]
You are right. A correct link that works is 

`https://russian--suitedocs.netlify.com/ru/user/introduction/user-interface/#_%D0%98%D0%BC%D0%BF%D0%BE%D1%80%D1%82_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85`

So we shoulnd't add `ru` in the file name, it is merely present in the directory name many levels above. If we use relative links we don't even have to make the links language specific (except the anchor part after `#`, if they have it).

**Comment by pgorod** [comment]
> I used the suggested environment , but I specifically added ifdef::env-github constructs. I also use this content at this github rep. in order to be able to refer to different versions of this Russian manual if it will be necessary in the future. And I really would like not to change these constructs if possible.

The future handling of multiple versions is something we will have to tackle for all languages, not just Russian.

I am trying to keep the complexity down, we will soon have a huge site with many languages and dozens of contributors. I really would like to avoid complicating simple things like links, for reasons that are external to our site.

If you really feel you need to keep a parallel version of what is here, why don't you simply open a free account on Netlify, and deploy exactly like we do? This way you wouldn't need to handle special cases for Github, it would be just a source repository. Netlify has many advantages.

**Comment by pgorod** [comment]
@likhobory about these new commits: 

1. Did you `pull` our `russian` branch before doing them?

2. Can you please direct your PR to our `russian` branch instead of `master`? You can edit this in the PR, you don't have to start a new one.

Thanks!

**Comment by likhobory** [comment]
1/ Yes
2/ ok

**Comment by pgorod** [comment]
@likhobory FYI our Netlify "build command" is this:

`bundle && hugo --enableGitInfo`

I think I could remove that git switch, because it is now included in all profiles in `netlify.toml` but I never tested it.

**Comment by likhobory** [comment]
>I think I could remove that git switch,

Agree. Deployed with new netlify.toml without any problem: https://vigilant-ride-fad5cc.netlify.com/ru

**Pull request closed without merging**
