### PR TITLE
Fixed broken link to v8 API

### PR DESCRIPTION
**Pull request by wenzdey**
The old version-8 page is a combination of both developer-setup-guide and postman-setup-guide page so I linked to main API page.

https://github.com/salesagility/SuiteDocs/issues/355

### CODE REVIEW

**Comment by wenzdey** [comment]
> 
> 
> LGTM, thanks for the contribution!

How can I get a mug? (per https://suitecrm.com/community-diary-sept-2019-edition/ )

**Comment by samus-aran** [comment]
Hey @wenzdey  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by samus-aran** [comment]
Hey @wenzdey 

You haven't yet submitted your shipping details for processing your gifts.

We ill be closing the form tonight. Hope to see your submission.

**Comment by wenzdey** [comment]
> 
> 
> Hey @wenzdey
> 
> You haven't yet submitted your shipping details for processing your gifts.
> 
> We ill be closing the form tonight. Hope to see your submission.

Whoops didn't see this until now. Submitted just in case it goes though. Thank you anyway!

**Pull request merged**
