### PR TITLE
Update _index.en.adoc

### PR DESCRIPTION
**Pull request by samus-aran**
Clearer description of beta assets

### CODE REVIEW

**Review by clemente-raposo — APPROVED** [review]

**Comment by pgorod** [comment]
I suggest explaining the difference between these two installation methods regarding Composer.

Something like: 

> this pre-built version includes a prepared vendor directory, so that you don't have to install Composer and run it.

**Comment by samus-aran** [comment]
Okay I hope that has made it abit clearer... I will also be upgrading hugo. Do spot checking on pages, languages and searching and everything appears to be fine. Also no more errors on builds (tho for the life of me can't get rid of warnings even applying the fixes!)

**Comment by likhobory** [comment]
@samus-aran 
The latest hugo versions with learn theme does not display TOC. The latest working version is v0.74.3

**Comment by pgorod** [comment]
If we have a specific error message maybe we can find something on the Learn theme Github, some open issue, probably even a fix. That project seems a bit slow, no new releases, but there are many people there participating and I think that often these incompatibilities are easy to restore with minor fixes.

**Comment by samus-aran** [comment]
> @samus-aran
> The latest hugo versions with learn theme does not display TOC. The latest working version is v0.74.3

Righty-o Thanks for pointing that out Greg!

We'll have a look on the theme, because the IgnoreJsonErrors fix was introduced in 0.77.0 :grimacing:

**Comment by pgorod** [comment]
Remember you can easily revert in Netlify if something's not quite ok with this version. The big Hugo upgrade is probably better to do in a separate branch, not master, so it can be tested more thoroughly.

What exactly are the JSON errors that made you want to use IgnoreJsonErrors?

Any way, I think you can aim for Hugo 0.85 or whatever the latest is, this always requires fixing some glitches so you might as well go for the latest version...

**Comment by samus-aran** [comment]
@pgorod upgrade PR noted :+1: 

The builds were failing because of the following errors:

9:52:35 AM: ERROR 2021/07/21 08:52:35 Failed to get JSON resource "https://api.github.com/users/horus68": Failed to retrieve remote file: Forbidden

https://app.netlify.com/sites/suitedocs/deploys/60f7dfdd9c47870008903477

You can see the PR builds if you click on the X (or ticks) next to the PR's commits.

You referred to this issue to here. https://github.com/salesagility/SuiteDocs/issues/483
To which the fix is to upgrade to 0.77 so that it won't fail the build (without it, regardless of a switch case (which the comments mention) it will fail as it returns an error).

**Comment by pgorod** [comment]
Ah ok, I remember that now. And what about the problems with 0.85, what are they?

I see the currently deployed version uses Hugo 0.85. @likhobory what exactly are the TOC problems you found? I don't see anything broken there...

**Comment by pgorod** [comment]
Also...

it's not entirely a good idea to ignore those errors. It's useful to ignore them when deploying for preview purposes, etc., but when it's time to move to live, it's nice to actually have those User's avatars there.

I think the GitHub API limits can be worked around by repeating the build process after the time limit elapses (maybe 4h, I don't remember). Since the assets are cached, instead of re-downloading existing avatars, it loads the ones that were missing, so eventually the build succeeds.

**Pull request merged**
