### PR TITLE
Google Sync and Elasticsearch Russian translation, reprise

### PR DESCRIPTION
**Pull request by pgorod**
Second attempt... see #174

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory this one looks right!

**Comment by likhobory** [comment]
Agree!

**Comment by pgorod** [comment]
So I can go ahead and merge this into master, right?

It basically includes the new stuff that is already in the English version, is that correct?

**Comment by likhobory** [comment]
Yes and yes.

**Comment by pgorod** [comment]
Done in #183 

Thanks for everything. Merry Christmas!

**Comment by likhobory** [comment]
Merry Christmas & Happy NY!

**Pull request merged**
