### PR TITLE
Fix #100, fix #254, fix #342 Upgrading Ubuntu in Netlify, FontAw…

### LINKED ISSUE #100: Stop top menu links from switching to English site
When browsing a non-english version of the Docs site, the top menu is translated, but if you click on the links, you are taken to the English version of the site, even if the page you wanted exists on the translated site you were browsing.

The menu links here need to be made more intelligent:

https://github.com/salesagility/SuiteDocs/blob/master/layouts/partials/menu.html#L121

### LINKED ISSUE #254: Try Ubuntu upgrade in Netlify
Netlify now has an option for Ubuntu 16.04 instead of the usual 14.04:

https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/

We should try it and see if it works well since it would allow some newer Hugo features, namely Hugo Pipes and Hugo extended.

### LINKED ISSUE #342: We can't use the latest Hugo versions
Subj.

The last working version is 0.54.

I propose to update the Learn theme to version [2.4](https://github.com/matcornic/hugo-theme-learn/releases/tag/2.4.0).

### PR DESCRIPTION
**Pull request by pgorod**
Well, fixing one led me to fix the other and suddenly all the upgrades were done!

Fixes #100, #342 and supersedes #393

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory the only thing I believe you will have to change on your side is the additional string I added in `en.toml`, please add it also in `ru.toml`

Thanks

**Comment by likhobory** [comment]
There are still a few warnings, but if you merge PR #429, then everything works, thanks!

**Comment by pgorod** [comment]
There is a problem with the search not working in the branch deploy of this PR. But I will try merging this to master, see if that makes a difference (search has always had problems running from branch deploys). If it doesn't work, I will revert to the previous deploy form Netlify (cool feature), until I find out how to fix it.

**Comment by pgorod** [comment]
Cool 🆒 , search works in `master`...

**Comment by likhobory** [comment]
@pgorod, now it doesn’t works when I use the Cyrillic alphabet..

**Comment by pgorod** [comment]
What doesn't work, the search?

**Comment by likhobory** [comment]
Yes.

**Comment by pgorod** [comment]
I opened an Issue with the Theme developers: 
https://github.com/matcornic/hugo-theme-learn/issues/365

**Pull request merged**
