### PR TITLE
Add description to hide/show columnChooser in ListViews (Russian…

### PR DESCRIPTION
**Pull request by likhobory**
@pgorod 
@Abuelodelanada 

See https://github.com/salesagility/SuiteCRM/pull/8100

I propose to add this description to the English part too.

### CODE REVIEW

**Comment by pgorod** [comment]
I updated the Russian branch with the latest changes form Master, so that this PR doesn't show all the other commits. 

But I need to ask you to not change anything in the `_source` folder, that is basically stuff from when we migrated from the old wiki into our current Hugo architecture, it's better to leave it as it was - it's just history. I need to remove that folder altogether one of these days.

**Comment by pgorod** [comment]
Sorry for the delay on this one, @likhobory

**Comment by likhobory** [comment]
@pgorod 
Please merge it into master ;)

**Comment by pgorod** [comment]
You speak wisely

**Pull request merged**
