### PR TITLE
Break down User Interface.ru.adoc

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by likhobory** [comment]
Hi, Pedro, good news. Unfortunately now I have no time, but I’ll definitely resolve these conflicts next week.

**Comment by pgorod** [comment]
I tried clicking "resolve conflicts" but it says the conflicts are too complex to resolve in web editor 🤔 

Maybe it's because I updated my `russian` branch with th recent changes from master, maybe if you do the same in your source branch at your repo, the conflicts will _automagically_ disappear.

**Comment by likhobory** [comment]
>maybe if you do the same in your source branch..

Did not work, but don't worry, I'll resolve conflicts locally, but a little bit later ...

**Comment by likhobory** [comment]
Done.

**Comment by pgorod** [comment]
Great! 

I've made a few more merges. If you update your repo from the current version (both `master` and `russian` have the same commits) you will see that we now have zero errors in `htmltest`. So anytime we make changes we can check if new errors appear, and we will now we have created new broken links.

I am running the tests locally with this command:

`rm -R public/* && hugo --enableGitInfo && ./bin/htmltest`

This does a clean recompile of everything (useful when you're checking in and out of branches, Hugo loses track of what is changed or not), and runs the tests.

I plan to add more tests, and to try and integrate this into GitHub/Netlify deploys one day.

**Comment by pgorod** [comment]
Also, coming soon: a broken down `Releases.adoc`, you can check progress here:

https://github.com/salesagility/SuiteDocs/compare/releases...cameronblaikie:releases

**Pull request merged**
