### PR TITLE
Update labels within raising issues doc

### PR DESCRIPTION
**Pull request by Mac-Rae**
Updating labels, please check that links work appropriately

### CODE REVIEW

**Comment by Mac-Rae** [comment]
I agree @pgorod, will take a look at that next time I get the chance

**Comment by pgorod** [comment]
What's the status on this one, Mac? Thanks

**Comment by Mac-Rae** [comment]
Not got round to it yet @pgorod will add it to my list for sprint end if I get the chance

**Comment by pgorod** [comment]
@Mac-Rae I did some work on this file about a month ago, related to another PR:
https://github.com/salesagility/SuiteDocs/commit/1655a14fa6b30dec957f5528edceabbc18eb986e

I am not too satisfied with all this - just copying labels' descriptions from GitHub doesn't add much value, and easily falls out of date...

**Comment by Mac-Rae** [comment]
Agreed, however, I was struggling to find a nicer way to include them. If you have any ideas let me know and we can take a look :+1:

**Comment by pgorod** [comment]
In terms of formatting and functionality, what I did earlier is ok, I guess (it gave me a lot of work!):

https://docs.suitecrm.com/community/raising-issues/

You can click and see the issues.

I don't know if some of the content of the current PR should be brought over to that table... but note how changed the format is now:
https://raw.githubusercontent.com/salesagility/SuiteDocs/master/content/community/raising-issues.adoc

If it's too much work, or you realize there's nothing to add, we can just close here. My feeling is that one day we will just remove this page and point people to Github...

**Comment by serhiisamko091184** [comment]
Hello all!
Closing this as agreed with @Mac-Rae. 
If we'd like to continue working on this PR, please, feel free to reopen it. 
Thanks a lot! 

Regards,
Serhii

**Pull request closed without merging**
