### PR TITLE
Rename _index.en.adoc to _index.ru.adoc

### PR DESCRIPTION
**Pull request by PechenyxaPRO**

### CODE REVIEW

**Comment by pgorod** [comment]
Why are you renaming this file? Perhaps you meant to create a copy of it instead?

**Comment by jack7anderson7** [comment]
Hi @PechenyxaPRO,

Can you confirm why it is you are renaming the file?

Thanks, 
Jack

**Comment by serhiisamko091184** [comment]
Hello @PechenyxaPRO, 

would you be so kind to update us on renaming (following previous comments)? 

Thanks in advance! 

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @PechenyxaPRO, 
one more time thank you for the PR and your time,
we’d like to continue working on this contribution and hope you can reopen it and update it when it’s appropriate for you.    
Thank you very much!

Regards,
Serhii

**Pull request closed without merging**
