### PR TITLE
Data Types

### PR DESCRIPTION
**Pull request by Mausino**
Description of each Data Type

### CODE REVIEW

**Comment by Mausino** [comment]
I did know to which branch i can pull request... there are maybe 20 of different branches

**Comment by pgorod** [comment]
You're almost there!

You have some `<br/>` codes showing. Try removing them and use a plus sign `+` as the last character of the line, to force a line break. I hope it works inside tables...

**Comment by pgorod** [comment]
I think you have to keep the actual line-break also. The `+` doesn't create a linebreak, it just tells Asciidoc to _keep_ the next line-break.

So try 

```
one line +
another line
```

Instead of what you're currently using, which is 

```
one line +another line
```

**Comment by Mausino** [comment]
@pgorod I think i am done 👍

**Comment by pgorod** [comment]
Thanks for all your patience Mausino! Next time will be easier, as you learn... 🎉

**Pull request merged**
