### PR TITLE
Update docs for ver. 7.11.3 (Russian)

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory I just updated the Russian branch so that this PR should now show only the new stuff you worked on. 
https://github.com/salesagility/SuiteDocs/compare/russian...likhobory:master

At the moment Github is still showing me more commits here, but hopefully it will update the diff after a while...

**Comment by pgorod** [comment]
It doesn't seem to be updating, maybe you can try editing something in the PR, to see if it triggers a new diff comparison? Maybe just change the name, or something more drastic like changing the base branch, and then changing it back to the initial value again.

**Comment by likhobory** [comment]
It works!

**Comment by likhobory** [comment]
Hi @pgorod 

Maybe it's time to merge this into master (and add the same Silent Upgrade description to the English part) ? :)

**Comment by pgorod** [comment]
Sorry, I had simply forgotten to merge this.

I'll have a look at the silent upgrade part, thanks.

**Comment by pgorod** [comment]
Ok, I did the silent upgrade section, thanks!

**Pull request merged**
