### PR TITLE
Update JSON-API.adoc

### PR DESCRIPTION
**Pull request by Sshahar**
Composer install explained

### CODE REVIEW

**Review by samus-aran — CHANGES_REQUESTED** [review]
There are a number of `composer install` referenced throughout the documentation site... I would suggest updating those to also include a link to obtain composer if they haven't done so already. What's the need to include phar? Would that be assumed if you install composer anyway? I don't think that would be necessary to explicitly say on these docs (SuiteCRM).

Either we reference composer similar to https://github.com/salesagility/SuiteDocs/blob/master/content/developer/automatedtesting/_index.en.adoc#L31
**This guide assumes you have already installed and set up a supported PHP version, MySQL 5.7, and [Composer](https://getcomposer.org/).**

But make it more generic e.g. This guide assumes you have already installed and set up appropriate environment and developer tools, e.g [Composer](https://getcomposer.org/)

**Comment by serhiisamko091184** [comment]
Hey @Sshahar, 

thank you for your contribution, 

if that is possible, we'd like you update your changes according previous comments. 

Thanks a lot in advance! 

Regards,
Serhii

**Comment by Sshahar** [comment]
I re-requested the merge. If something else was required I couldn't understand

**Comment by serhiisamko091184** [comment]
Hello @Sshahar, 

Thanks for your quick response,

The command 'composer install' is referenced not only in this file, that is why in the first passage of the very first comment there is a suggestion to apply changes to those, not only in this particular place (to make it consistent).

Further there is a question particularly about phar - is there a specific reason we need to mention it?

At the same time there are some examples of possible implementation of referencing composer and another suggestion of a more desirable generic format to have.

Thanks in advance!

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @Sshahar,

thanks one more time for bringing this PR to us, 

as repo 'Sshahar:patch-1' has been deleted I closed the current PR. 
If you would like to continue working on the suggested changes, feel free to reopen it / create a new one when you are ready. 

Thanks a lot! 

Regards,
Serhii

**Pull request closed without merging**
