### PR TITLE
Update and rename Users.adoc to Users.pl.adoc

### PR DESCRIPTION
**Pull request by m4ax92**

### CODE REVIEW

**Comment by pgorod** [comment]
@m4ax92 what exactly are you trying to do? Are you going for a full translation of the Docs site?

You should keep this work to yourself until it's more advanced; you can work on your own Repo. You would only create a PR here (a single one, not one per page!) when you have a nice group of pages that is worth including in the site...

**Comment by m4ax92** [comment]
> @m4ax92 what exactly are you trying to do? Are you going for a full translation of the Docs site?
> 
> You should keep this work to yourself until it's more advanced; you can work on your own Repo. You would only create a PR here (a single one, not one per page!) when you have a nice group of pages that is worth including in the site...

1. yes, I want to make full translation of documentation
2. i saw this guide ( [link](https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/) )so i made everything described in it :) thanks for hint, i will do as you say :)

**Comment by pgorod** [comment]
Yes, translating the whole site (or a large part of it) isn't a "simple edit".

The other guide is much better for this task: 
https://docs.suitecrm.com/community/contributing-to-docs/local-setup/

**Comment by samus-aran** [comment]
Hey @m4ax92. Hope you're doing well, and if you need any help to do a mass translation then feel free to mention me on your forked repo or jump onto the [SuiteCRM forums](https://community.suitecrm.com/) and PM me (my username is the same there). I'll close these PRs just now and hopefully see your contribution in the future. :+1:

**Pull request closed without merging**
