### PR TITLE
Update webserver-setup-guide.adoc

### PR DESCRIPTION
**Pull request by johnrigler**
Typo: 
Helpfull is no longer a word: use "Helpful" instead.

### CODE REVIEW

**Comment by pgorod** [comment]
There are 2 more instances of that word with the wrong spelling in the same file, while you're at it, you might as well fix them all :-)

Thank you

**Comment by johnrigler** [comment]
OK, I have updated. Not sure if I delete this pull request and add another OR just update it. Looking...

**Comment by pgorod** [comment]
You update din a different branch.

If you edit the file in the same branch, it's much easier. 

Just change your file here

https://github.com/johnrigler/SuiteDocs/blob/patch-1/content/8.x/admin/installation-guide/webserver-setup-guide.adoc

And the changes should be picked up here in the PR, without any other action needed.

**Comment by serhiisamko091184** [comment]
Hi @johnrigler,

thanks one more time for your contribution, 

I'm closing this one as I merged updates from: 
https://github.com/salesagility/SuiteDocs/pull/637

Thanks a lot! 

Regards,
Serhii

**Pull request closed without merging**
