### PR TITLE
Break down Workflow.ru.adoc in 2 smaller files

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
Hi Greg

There is something wrong with this pull request, too many file changes are included...

**Comment by likhobory** [comment]
Hi Pedro,

I updated my repo from the SuiteDocs/master branch, added some changes and made PR into russian branch, what's wrong?

**Comment by Dillon-Brown** [comment]
@likhobory I think the issue is that this PR is showing 837 changes. It's because the file permissions have changed from 100755 to 100644. You can normally prevent this through the git config by running this command:

```
git config --global core.fileMode false
```

**Comment by pgorod** [comment]
I made the permissions changes, and I should be doing that setting :-)

Anyway, I think the problem is that my Russian branch isn't up to date with my master, I will fix that.

**Pull request merged**
