### PR TITLE
Add Russian translation for SCRM-Analytics-Getting-Started ver. 1.1

### PR DESCRIPTION
**Pull request by likhobory**

### CODE REVIEW

**Comment by pgorod** [comment]
@likhobory off-topic, but you might want to have a look at this:

https://github.com/matcornic/hugo-theme-learn/issues/365#issuecomment-713471649

**Comment by likhobory** [comment]
Thanks Pedro, it works!!

**Comment by pgorod** [comment]
I am unsure about how to handle this search fix. Ideally the fix would go into the theme and we would upgrade the theme here. It's just to avoid diverging from the theme in ways that are hard to understand later on...

If we do go ahead with the fix immediately, then at least it should be a separate PR so that it's properly documented that we might want to revert it after the theme includes the fix.

This is just an opinion, I am not too sure about it. It's up to the maintainers.

**Comment by likhobory** [comment]
Yes, you're right, I'll make a separate PR from another branch.

**Pull request merged**
