### PR TITLE
Update Customization.adoc

### PR DESCRIPTION
**Pull request by kunanSA**

### CODE REVIEW

**Comment by pgorod** [comment]
I thought that you created the file in 
`custom/Extension/application/Ext/Api/V8/`

and then the Quick Repair and Rebuild would move it to 
`custom/application/Ext/Api/V8/`

am I wrong?

**Comment by kunanSA** [comment]
> I thought that you created the file in `custom/Extension/application/Ext/Api/V8/`
> 
> and then the Quick Repair and Rebuild would move it to `custom/application/Ext/Api/V8/`
> 
> am I wrong?

The repair does not move the files to the specified folder and does not alter them if you create them in  `custom/application/Ext/Api/V8/`. I don't know if it's a bug or it was always like this

**Comment by pgorod** [comment]
What happens if you place the files in custom/Extension and run the QR&R?

If it works, since that is the regular way of doing things, I believe that's what we should be recommending in the docs.

**Review by serhiisamko091184 — APPROVED** [review]

**Comment by serhiisamko091184** [comment]
Hello @kunanSA,

thanks for contributing to the SuiteCRM project! 

Regards,
Serhii

**Pull request merged**
