### PR TITLE
Update to SuiteCRM's Target Lists webpage

### PR DESCRIPTION
**Pull request by devincurrie**
Hello, this is my first edit. Changes proposed:
1) deleted table at beginning as it shouldn't be part of the documentation
2) added table "Target List Types" section obtained from:
https://support.sugarcrm.com/Documentation/Sugar_Versions/8.0/Pro/Application_Guide/Target_Lists/#Target_List_Types
Note: info is relevant to current version of SuiteCRM

Reference:
https://pgorod.github.io/Concepts-Campaigns-Email-Templates/

### CODE REVIEW

**Comment by pgorod** [comment]
Hi, thanks for these edits!

You mentioned on Disqus that the instruction didn't say a fork was necessary. You're right that is not explained there, but the instruction does work. Github takes care of all that, whenever you edit a file in another user's repository, where you don't have write access.

About the table on top that you removed, that is not a table, and it needs to be there. It's called front-matter, it's for Hugo, and it basically defines the article title and position in the menu.

You can see the effect of your edits rendered in the "checks" section of this PR. Following that link and then navigating to the edited page will take you [here](https://deploy-preview-338--suitedocs.netlify.com/user/core-modules/target-lists/)

That broken formatting you see is due to the removal of the front-matter.

Another **important** issue (sorry, it should have occurred to me to mention this before). We shouldn't take SugarCRM's content as we're not sure of the legal implications of that, it's probably copyrighted unless it was contributed by the community, but I don't think so. So you would have to write your own sentences, not just copy theirs. If you are willing, of course. 

Thanks!

**Comment by likhobory** [comment]
> you would have to write your own sentences

As an alternative you can do a reverse translation from [this](https://github.com/likhobory/SuiteDocs/blob/master/content/user/core-modules/Target%20Lists.ru.adoc) Russian page.

**Comment by devincurrie** [comment]
Hi sorry was travelling over the last few days. Thanks for clarifying on front matter.

> Another important issue (sorry, it should have occurred to me to mention this before). We shouldn't take SugarCRM's content as we're not sure of the legal implications of that, it's probably copyrighted unless it was contributed by the community, but I don't think so. So you would have to write your own sentences, not just copy theirs. If you are willing, of course.

It will be more work/time to rewrite sentences due to copyright concerns. It would be great if we have black/white answer from SugarCRM if we can copy their content, as applicable, as long their credit remains attached?

For documentation written in multiple languages, how do we ensure consistency? In other words, is there a base language (e.g. English) to translate from or are articles developed independently in its respective languages?

Thanks,

Devin

**Comment by pgorod** [comment]
I don't think we can expect SugarCRM to play nice to us. If you want to try and get a nice black or white answer from them, go ahead, but I wouldn't bet on your success :-)

And we can't afford any legal risks here. Unless they have a clear license statement, I don't think we should risk having their big legal team harassing us. Not worth it, any way.

About the international versions - normally the English version is the standard, and others translate. But there are a few exceptions, since @likhobory was already ahead of us in some parts of the documentation when we started. So there are some bits we need to get from the Russian site, but it's not much.

**Comment by likhobory** [comment]
As @pgorod already noted, it depends on which document was previously created. Of course, most of the Russian documents are a translation of the official documentation for SUGAR CE with an additional description of SuiteCRM functionality. But some Russian documents were created earlier than English, in this case the developers included a translation into the official documentation.

The Russian analogue of the table you proposed  is almost a literal translation from the official site (with very small and unimportant changes). So, if you translate the Russian version into English, then, on the one hand, you will save your time, on the other hand, you will get a description of the same functionality, but slightly different from the original text.

If you decide to translate Russian text, feel free  to ask questions on the terminology if you are confused by the result of the translation.

**Comment by devincurrie** [comment]
Alright. Rather than getting in touch with Sugar, how about consulting with Free Software Foundation to ask for their interpretation if it is permissible to copy from Sugar's CE 6.5 documentation and revise from there? FSF was mentioned in the LICENSE.txt file attached.
[LICENSE.txt](https://github.com/salesagility/SuiteDocs/files/3602041/LICENSE.txt)

https://support.sugarcrm.com/Documentation/Unsupported_Versions/Sugar_6.5/index.html

**Comment by pgorod** [comment]
I (personally) don't think it's worth the effort, because Sugar's documentation, as far as I know, was not contributed by the community, it was payed by them, and there is no license on their site giving it away. I don't see how it could possibly be made available to a competitor, unless they wanted to give it away, which I don't expect they will...

It would be a different story with the community forums they had. That had a lot of content provided by community members, and now it's mostly gone, although some of it can still be accessed in the Wayback machine.

**Comment by pgorod** [comment]
Their Documentation site has this at the bottom:
image
So that will surely not be included in any open-source license they had in the code, available on a different site...

**Pull request closed without merging**
